### ISSUE TITLE
Admin - General: Archive should not be included since there's no Archive found in the design and pls apply this to all page link acf

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#10]
![image](https://cloud.githubusercontent.com/assets/13363508/9457049/7163718a-4b11-11e5-9784-51baecb70d4e.png)

**Comment by arielcebudigital** [comment]
Hi Mae, it won't fix since it's the new default select for ACF Page Link. Plugin issue....
