### ISSUE TITLE
Admin: Our Services - no latest featured image found

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#11]
![image](https://cloud.githubusercontent.com/assets/13363508/9457145/35679e3a-4b12-11e5-825c-2f45f425eaa0.png)

<b>If you pull out images under Our Services latest image, what if there's no image uploaded? it's not right to display the Default Image as Final in the homepage</b>

**Comment by arielcebudigital** [comment]
This area is not ACF, it is the latest featured image for Our Services post :-)

**Comment by maehtitan** [comment]
<b>Yes, it's not an ACF.
Scenario: If I am a client and I haven't uploaded an image to the Services post, I won't agree that the image I will see in the front-end is the default image. I believe you can pull out and retain the last services post with image in the functionality or make the featured image as mandatory at the backend.</b>

**Comment by arielcebudigital** [comment]
I created new field for image.
