### ISSUE TITLE
Homepage - Mobile: Everything is too big, please have it design like the Portrait View, apply fixes in the S4 landscape view too

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#20]
Device: Itouch 5 (landscape)

![image](https://cloud.githubusercontent.com/assets/13363508/9459425/f0a0b928-4b2d-11e5-9a53-f9e3d9c26681.png)

**Comment by arielcebudigital** [comment]
The font-size I used is 14px, and once it goes to tablet it will change to 12px.. if you can check some mobile design you can see that mobile footer font-size is bigger than desktop.

**Comment by maehtitan** [comment]
"if you can check some mobile design you can see that mobile footer font-size is bigger than desktop."

- actually it only exist on your implementation, I've tried checking on some other sites, portrait views are the same with landscape views

**Comment by maehtitan** [comment]
Fixed in S4 but not in Itouch

**Comment by arielcebudigital** [comment]
Please attach screenshot for itouch, thanks...

**Comment by maehtitan** [comment]
@arielcebudigital 

Current view for Itouch are only recommended for desktop and ipad view...

![image](https://cloud.githubusercontent.com/assets/13363508/9624162/7d25f472-517c-11e5-9fa5-2b1d99fcf39a.png)
