### ISSUE TITLE
Our Services: Active State is not applied

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#21]
![image](https://cloud.githubusercontent.com/assets/13363508/9459600/13dffdc0-4b30-11e5-83dc-7ba34579a998.png)

**Comment by arielcebudigital** [comment]
PSD layout issue, try to check the news page, it does not have hover/active state, for consistency lets not put the active state since it doesn't make sense to to click it then redirect to it's pages itself..

**Comment by maehtitan** [comment]
<b>News page does have a hover state obviously because list of news hover state is the same with the  Our Services page it's just that the graphic artist who cloned the .psd file forgot to renamed it to News text (design error)</b>

**Comment by christiancebudigital** [comment]
Hi Maeh,

This is a design error, i've talked to bernard on this issue, and we both agreed to make it consistent with other page, will not make this active/hover state, since this is a sidebar title, this is a design error, will flagged this one as wont fix.

Thanks,
Christian

**Comment by maehtitan** [comment]
@christiancebudigital Thanks. If that is a title might as well remove the (>) icon so that it won't represent as a link.

**Comment by arielcebudigital** [comment]
removing icon in header sidebar

**Comment by maehtitan** [comment]
@arielcebudigital Pls have it remove too in News and News Single page thanks :)

**Comment by arielcebudigital** [comment]
I already remove it..:-)
