### ISSUE TITLE
Admin - Our Services: Default order should be the same with the admin Our Services custom post, latest should be placed above not at the bottom

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#22]
<b>Same like the News sidebar order</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9459705/ffcd7050-4b30-11e5-9194-dd37b8bf0995.png)

**Comment by arielcebudigital** [comment]
Hi Mae, I put this invalid because you forgot to click the update button. once you click that button the ordering will be same in the admin.

**Comment by maehtitan** [comment]
This is not invalid, because in the first place I haven't touch the Order Section at the admin I only add Services items

**Comment by arielcebudigital** [comment]
That's the problem you want to make it the same yet you did not update it, the standard ordering we used 

here you can look at it.

https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/custom-posts
