### ISSUE TITLE
Our Services: I see 3 lines of text

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#23]
![image](https://cloud.githubusercontent.com/assets/13363508/9459753/8784fd1a-4b31-11e5-88c5-0bb2fd2bcfef.png)

**Comment by arielcebudigital** [comment]
Hi Mae, this one is invalid, because from 4 lines it will reduce if there is no image since the width used now is full width, you can ask Christian about this matter since he is the one who created the project scope.

**Comment by maehtitan** [comment]
The project scope is right, this ticket is not invalid and is meant to be fixed because this is doable, I always reported this kind issue on some other project and no issue on dev part

Sample issue link here: https://github.com/titan-cebu/Tates-Coating/issues/84
