### ISSUE TITLE
Sidebar - Section: Since you added a hover state behaviour of the sidebar services list, might as well add an active state when that particular page is open

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#26]
<b>Apply enhancement in Our-Services and Our-Services Single page and also in the News and News Single Page Sidebar</b>

![image](https://cloud.githubusercontent.com/assets/13363508/9459940/a549dc06-4b33-11e5-8d49-327587514e58.png)

**Comment by arielcebudigital** [comment]
It's done :-) :+1:
