### ISSUE TITLE
Footer Section: Missing active state behaviour

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#3]
![image](https://cloud.githubusercontent.com/assets/13363508/9433322/81492710-4a63-11e5-90bd-a855841e7b84.png)

**Comment by arielcebudigital** [comment]
Check this PSD layout for contact-us, it is the same with sitemap

![contact](https://cloud.githubusercontent.com/assets/11186408/9513268/7fd77832-4cc0-11e5-8279-84af315819b6.png)

**Comment by maehtitan** [comment]
<b>main navigation layout is completely different from the footer behavior, when hover state is red obviously the active state is red</b>
