### ISSUE TITLE
Sitemap: Remove unnecessary pages

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#32]
![image](https://cloud.githubusercontent.com/assets/13363508/9484433/b4f0c2cc-4bde-11e5-8010-c9e544d0d928.png)

**Comment by arielcebudigital** [comment]
Hi Mae, Gallery is a standard page for titan even though they don't have a layout for this page., you can refer it Bernard :-)

**Comment by maehtitan** [comment]
Mark as on wontfix as advice by Bernard, Standard will be change today.
