### ISSUE TITLE
News and Our Services - Mobile: Images are stretched and pixelated.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Dynamic-Group#34]
Devices: 

Itouch (landscape)
S4 (portrait and landscape)
Ipad (landscape)

![image](https://cloud.githubusercontent.com/assets/13363508/9484372/af63eb78-4bdd-11e5-8f96-46137b13e3a2.png)

**Comment by arielcebudigital** [comment]
Hi Mae, i put invalid for this one because the image is 100%, so basically it will fit the width once you change the view either portrait or landscape in mobile and tablet., Basic Responsive Layout.

**Comment by maehtitan** [comment]
This is not invalid, its the code you used, image width set to 100% means stretching small images to fit the width of the devices, use the max-width instead.

**Comment by maehtitan** [comment]
<b>Fixed in Ipad and S4 but still recurring in Itouch (landscape)</b>

**Comment by arielcebudigital** [comment]
please post screenshot we cannot replicate the issue, thanks

**Comment by arielcebudigital** [comment]
we don't have itouch device

**Comment by maehtitan** [comment]
@arielcebudigital it looks like this in itouch 5 both News and Our Services
cache already cleared 100% :)
![image](https://cloud.githubusercontent.com/assets/13363508/9624078/b44e7132-517b-11e5-9669-a37f97b54adc.png)

**Comment by arielcebudigital** [comment]
@maehtitan please upload high res images.

**Comment by maehtitan** [comment]
@arielcebudigital even if it is high and low res images, it shouldn't be stretched like that in Itouch 5 which stretched the small image

**Comment by christiancebudigital** [comment]
Hi Maeh,

For this issue, we will just upload bigger image that will be required in the user guide, and for that bigger image being uploaded, it will generate an image that will fit on the actual device, and for that we will not have issue on stretched images.

Thanks,
Christian

**Comment by maehtitan** [comment]
Hello @christiancebudigital why is it the removing the code width:100% or making it to max-width will fix the issue?

![image](https://cloud.githubusercontent.com/assets/13363508/9625503/46afb718-5189-11e5-9d22-bda12f29a602.png)

**Comment by christiancebudigital** [comment]
Hi @maehtitan 

I am confused on your question, please expound more, image also is not displaying.

Thanks,
Christian

**Comment by maehtitan** [comment]
I was checking the code, it is the reason why images expanded due to that width: 100% in line 912 and also in sass folder line 1156

![image](https://cloud.githubusercontent.com/assets/13363508/9625743/f23d4e96-518a-11e5-9926-3f0ad4c7e6a7.png)

**Comment by christiancebudigital** [comment]
Hi @maehtitah, 

Since this is a responsive website, we make the image fit the width of mobile devices, that is why certain media query are applied on the images,  and since we will upload bigger images, stretched images are not an issue to use thus, image regeneration will be applied on the site, hope that answer your question.

Thanks,
Christian
